$domain_name = "sitename.com"
$vagrant_ip = "33.33.164.176"
$cpus = 2
$memory = 2048
$box_path = "./devops/builds"
$box_name = "sitename-web.box"
$base_ovf = "ruby-mysql-latest"

# TODO: check for newer versions
`wget -P ./devops/tmp wget http://devops.cloudspace.com/images/#{$base_ovf}.ovf` unless File.exist?('devops/tmp/#{$base_ovf}.ovf')
`wget -P ./devops/tmp http://devops.cloudspace.com/images/#{$base_ovf}-disk1.vmdk` unless File.exist?('devops/tmp/#{$base_ovf}-disk1.vmdk')
`cd ./devops && packer build packer.json` unless File.exist?(File.join($box_path, $box_name))

Vagrant.configure(2) do |config|
  org = $domain_name
  config.vm.box = $box_name
  config.vm.box_url = File.join($box_path, $box_name)
  config.ssh.private_key_path = ['devops/vagrant.pem', File.join(ENV['HOME'], '.ssh', 'id_rsa')]
  config.ssh.forward_agent = true
  config.vm.network "private_network", ip: $vagrant_ip
  config.vm.synced_folder "./", "/srv/#{org}", type: "nfs"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", $memory, "--name", $domain_name,"--cpus", $cpus]
    # v.gui = true
  end
end
