$domain_name = "cloudspace.com"
$vagrant_ip = "33.33.33.55"
$cpus = 2
$memory = 2048

Vagrant.configure(2) do |config|
  org = $domain_name
  config.vm.box = "vagrant.box"
  config.vm.box_url = "file://vagrant/vagrant.box"
  config.ssh.private_key_path = [File.join(ENV['HOME'], '.ssh', 'vagrant.pem'), File.join(ENV['HOME'], '.ssh', 'id_rsa')]
  config.ssh.forward_agent = true
  config.vm.network "private_network", ip: $vagrant_ip
  config.vm.synced_folder "./", "/srv/#{org}", type: "nfs"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", $memory, "--name", $domain_name,"--cpus", $cpus]
    # v.gui = true
  end
end
