#!/bin/bash -eux

rbenv rehash
gem install rails
gem install mysql2
gem install pg
gem install nokogiri
gem install sass-rails
gem install uglifier
gem install coffee-rails
gem install execjs
gem install jquery-rails
gem install turbolinks
gem install jbuilder
gem install sdoc
gem install bcrypt
gem install unicorn
gem install capistrano-rails
gem install thread_safe
gem install aws-sdk
gem install therubyracer
gem install devise
gem install cancan
gem install rolify
gem install haml
gem install slim
gem install paperclip
gem install sshkey
gem install twitter-bootstrap-rails
gem install less-rails
gem install omniauth-github
gem install binding_of_caller
gem install net-ssh
gem install rspec
gem install rspec-rails
gem install shoulda
gem install database_cleaner
gem install factory_girl_rails
gem install faker
gem install yard
gem install yard-activerecord
gem install redcarpet
gem install github-markup
gem install pry-byebug
gem install pry-rails
gem install rails_best_practices
gem install rubocop
gem install ruby-progressbar
gem install metric_fu
gem install guard-bundler
gem install guard-rails
gem install guard-rspec
gem install librarian-chef
